// Copyright (c) 1994-2011 Georgia Tech Research Corporation, Atlanta, GA
// This file is part of FalconView(tm).

// FalconView(tm) is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// FalconView(tm) is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.

// You should have received a copy of the GNU Lesser General Public License
// along with FalconView(tm).  If not, see <http://www.gnu.org/licenses/>.

// FalconView(tm) is a trademark of Georgia Tech Research Corporation.



// mkdir.c

#include "stdafx.h"
#include "err.h"

int FIL_create_directory(const char *directory)
{
   // returns FALSE for failure
   if (CreateDirectory(directory, NULL) == FALSE)
   {
      const int MESSAGE_LEN = 255;
      char message[MESSAGE_LEN];
      long int error;

      // get WIN32 error code generated by CreateDirectory()
      error = GetLastError();

      // log directory name and error code
      sprintf_s(message, MESSAGE_LEN, "Failed creating %s\nGetLastError() == %lx", 
         directory, error);
      INFO_report(message);

      return FAILURE;
   }
            
   return SUCCESS;
}

