// Copyright (c) 1994-2009 Georgia Tech Research Corporation, Atlanta, GA
// This file is part of FalconView(tm).

// FalconView(tm) is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// FalconView(tm) is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.

// You should have received a copy of the GNU Lesser General Public License
// along with FalconView(tm).  If not, see <http://www.gnu.org/licenses/>.

// FalconView(tm) is a trademark of Georgia Tech Research Corporation.

#if !defined(AFX_FIELDS_H__4C8FEF8F_596C_481B_ABC4_6CC80550E137__INCLUDED_)
#define AFX_FIELDS_H__4C8FEF8F_596C_481B_ABC4_6CC80550E137__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CField;

/////////////////////////////////////////////////////////////////////////////
// CFields wrapper class

class CFields : public COleDispatchDriver
{
public:
	CFields() {}		// Calls COleDispatchDriver default constructor
	CFields(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CFields(const CFields& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	void Refresh();
	CField GetItem(const VARIANT& Index);
	void Delete(const VARIANT& Index);
	void Append(LPCTSTR Name, long Type, long DefinedSize, long Attrib, const VARIANT& FieldValue);
	void Update();
	void Resync(long ResyncValues);
	void CancelUpdate();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FIELDS_H__4C8FEF8F_596C_481B_ABC4_6CC80550E137__INCLUDED_)
